#!/bin/bash
# Copyright 2012-2014 MongoDB, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function p() {
    local params=$(sed -e 's|["]|\\\"|g' $1)
    echo $(eval echo \"$params\")
} 

function r() {
    echo $1| cut -d'/' -f 2
}

function a() {
    echo $(cd $(dirname $1); pwd)/$(basename $1)
}

WORKSPACE=~/tmp/orchestrations
LOGPATH=$WORKSPACE
DBPATH=$WORKSPACE

rm -fr $WORKSPACE
mkdir $WORKSPACE

SSL_FILES=$(a ./ssl-files)
BASE_URL=http://localhost:8889

echo "DBPATH:$DBPATH"
echo "LOGPATH:$LOGPATH" 

echo "Posting a request from $1 to $BASE_URL..."
curl -H "Accept: application/json" -X POST -d "$(p $1)" $BASE_URL/$(r $1)
echo ""
curl -i -H "Accept: application/json" -X GET $BASE_URL/$(r $1)
echo ""
