name: Tests

on:
  push:
    branches: ['master']
  pull_request:

jobs:
  test-rs:
    runs-on: ubuntu-22.04
    name: Test Replica Sets
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          cache: 'pip'
          cache-dependency-path: 'setup.py'
      - name: Install MongoDB
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
      - name: Install deps
        run: |
          pip install -e .
          pip install pytest
      - name: Run Tests
        run: |
          pytest -raXs -v --durations 10 --color=yes tests/test_replica_sets.py

  test-other:
    runs-on: ubuntu-22.04
    name: Test Other Files
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          cache: 'pip'
          cache-dependency-path: 'setup.py'
      - name: Install MongoDB
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
      - name: Install deps
        run: |
          pip install -e .
          pip install pytest
      - name: Run Tests
        run: |
          pytest -raXs -v --durations 10 --color=yes --ignore=tests/test_replica_sets.py