name: Tests

on:
  push:
    branches: ['master']
  pull_request:

jobs:
  test-rs:
    runs-on: ubuntu-latest
    name: Test Replica Sets
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          cache: 'pip'
          cache-dependency-path: 'setup.py'
      - name: Run tests
        run: |
          pip install -e .
          pip install pytest
          pytest tests/test_replica_sets.py

  test-other:
    runs-on: ubuntu-latest
    name: Test Other Files
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          cache: 'pip'
          cache-dependency-path: 'setup.py'
      - name: Run tests
        run: |
          pip install -e .
          pip install pytest
          pytest  --ignore=tests/test_replica_sets.py